// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.activate.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.app.feature.activate.data.model.ActivateModel
import com.example.app.feature.activate.data.repository.ActivateRepository
import com.example.app.utils.UiState
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class ActivateViewModel @Inject constructor(
    private val repository: ActivateRepository
) : ViewModel() {

    private val _uiState = MutableStateFlow<UiState<ActivateModel>>(UiState.Loading)
    val uiState: StateFlow<UiState<ActivateModel>> = _uiState.asStateFlow()

    init {
        fetchData()
    }

    fun fetchData() {
        viewModelScope.launch {
            repository.fetchActivate().collect { state ->
                _uiState.value = state
            }
        }
    }
}
