#!/usr/bin/env bash

# This script generates a full feature folder structure and required files
# for an Android Jetpack Compose MVVM + Clean Architecture project.

set -e

BASE_PACKAGE="com.example.app"
BASE_SRC_PATH="app/src/main/java/com/example/app"

show_help() {
    echo "Usage: ./new_feature.sh <feature_name>"
    echo ""
    echo "This script auto-generates a full feature folder structure following Clean Architecture."
    echo "The feature name should be in lowercase (e.g., home)."
    echo ""
    echo "Example:"
    echo "  ./new_feature.sh home"
    echo "  ./new_feature.sh profile"
}

if [ "$#" -ne 1 ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    show_help
    exit 0
fi

FEATURE="$1"
# Capitalize the first letter for the PascalCase version (POSIX compliant)
PASCAL_NAME=$(echo "$FEATURE" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')

FEATURE_PATH="${BASE_SRC_PATH}/feature/${FEATURE}"
PACKAGE_NAME="${BASE_PACKAGE}.feature.${FEATURE}"

if [ -d "$FEATURE_PATH" ]; then
    echo "Error: Feature folder '$FEATURE_PATH' already exists."
    echo "Aborting to prevent overwriting existing files."
    exit 1
fi

echo "Generating Clean Architecture feature: $FEATURE (Class prefix: $PASCAL_NAME)"

# Create directories
mkdir -p "${FEATURE_PATH}/domain/model"
mkdir -p "${FEATURE_PATH}/domain/repository"
mkdir -p "${FEATURE_PATH}/domain/usecase"
mkdir -p "${FEATURE_PATH}/data/model"
mkdir -p "${FEATURE_PATH}/data/remote"
mkdir -p "${FEATURE_PATH}/data/repository"
mkdir -p "${FEATURE_PATH}/presentation/ui"
mkdir -p "${FEATURE_PATH}/presentation/viewmodel"
mkdir -p "${FEATURE_PATH}/presentation/navigation"
mkdir -p "${FEATURE_PATH}/di"

# File Paths
# Domain Layer
ENTITY_FILE="${FEATURE_PATH}/domain/model/${PASCAL_NAME}Entity.kt"
REPO_INTERFACE_FILE="${FEATURE_PATH}/domain/repository/${PASCAL_NAME}Repository.kt"
USECASE_FILE="${FEATURE_PATH}/domain/usecase/Get${PASCAL_NAME}UseCase.kt"

# Data Layer
DTO_FILE="${FEATURE_PATH}/data/model/${PASCAL_NAME}Dto.kt"
API_FILE="${FEATURE_PATH}/data/remote/${PASCAL_NAME}ApiService.kt"
REPO_IMPL_FILE="${FEATURE_PATH}/data/repository/${PASCAL_NAME}RepositoryImpl.kt"

# Presentation Layer
VIEWMODEL_FILE="${FEATURE_PATH}/presentation/viewmodel/${PASCAL_NAME}ViewModel.kt"
SCREEN_FILE="${FEATURE_PATH}/presentation/ui/${PASCAL_NAME}Screen.kt"
NAVHOST_FILE="${FEATURE_PATH}/presentation/navigation/${PASCAL_NAME}Host.kt"

# DI Layer
MODULE_FILE="${FEATURE_PATH}/di/${PASCAL_NAME}Module.kt"

# --- DOMAIN LAYER ---

# 1. Domain Entity
cat <<EOF > "$ENTITY_FILE"
// Auto-generated by new_feature.sh
package ${PACKAGE_NAME}.domain.model

data class ${PASCAL_NAME}Entity(
    val id: Int,
    val name: String,
    val description: String
)
EOF

# 2. Domain Repository Interface
cat <<EOF > "$REPO_INTERFACE_FILE"
// Auto-generated by new_feature.sh
package ${PACKAGE_NAME}.domain.repository

import ${PACKAGE_NAME}.domain.model.${PASCAL_NAME}Entity
import ${BASE_PACKAGE}.utils.UiState
import kotlinx.coroutines.flow.Flow

interface ${PASCAL_NAME}Repository {
    suspend fun fetch${PASCAL_NAME}(): Flow<UiState<${PASCAL_NAME}Entity>>
}
EOF

# 3. Domain UseCase
cat <<EOF > "$USECASE_FILE"
// Auto-generated by new_feature.sh
package ${PACKAGE_NAME}.domain.usecase

import ${PACKAGE_NAME}.domain.model.${PASCAL_NAME}Entity
import ${PACKAGE_NAME}.domain.repository.${PASCAL_NAME}Repository
import ${BASE_PACKAGE}.utils.UiState
import kotlinx.coroutines.flow.Flow
import javax.inject.Inject

class Get${PASCAL_NAME}UseCase @Inject constructor(
    private val repository: ${PASCAL_NAME}Repository
) {
    suspend operator fun invoke(): Flow<UiState<${PASCAL_NAME}Entity>> {
        return repository.fetch${PASCAL_NAME}()
    }
}
EOF

# --- DATA LAYER ---

# 4. Data Dto
cat <<EOF > "$DTO_FILE"
// Auto-generated by new_feature.sh
package ${PACKAGE_NAME}.data.model

import com.google.gson.annotations.SerializedName
import ${PACKAGE_NAME}.domain.model.${PASCAL_NAME}Entity

data class ${PASCAL_NAME}Dto(
    @SerializedName("id")
    val id: Int?,
    @SerializedName("name")
    val name: String?,
    @SerializedName("description")
    val description: String?
)

// Extension function to map DTO to Domain Entity
fun ${PASCAL_NAME}Dto.toEntity(): ${PASCAL_NAME}Entity {
    return ${PASCAL_NAME}Entity(
        id = this.id ?: 0,
        name = this.name.orEmpty(),
        description = this.description.orEmpty()
    )
}
EOF

# 5. ApiService
cat <<EOF > "$API_FILE"
// Auto-generated by new_feature.sh
package ${PACKAGE_NAME}.data.remote

import ${PACKAGE_NAME}.data.model.${PASCAL_NAME}Dto
import retrofit2.Response
import retrofit2.http.GET

interface ${PASCAL_NAME}ApiService {
    @GET("/${FEATURE}")
    suspend fun get${PASCAL_NAME}Data(): Response<${PASCAL_NAME}Dto>
}
EOF

# 6. Repository Implementation
cat <<EOF > "$REPO_IMPL_FILE"
// Auto-generated by new_feature.sh
package ${PACKAGE_NAME}.data.repository

import ${PACKAGE_NAME}.data.remote.${PASCAL_NAME}ApiService
import ${PACKAGE_NAME}.data.model.toEntity
import ${PACKAGE_NAME}.domain.model.${PASCAL_NAME}Entity
import ${PACKAGE_NAME}.domain.repository.${PASCAL_NAME}Repository
import ${BASE_PACKAGE}.utils.UiState
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class ${PASCAL_NAME}RepositoryImpl @Inject constructor(
    private val apiService: ${PASCAL_NAME}ApiService
) : ${PASCAL_NAME}Repository {

    override suspend fun fetch${PASCAL_NAME}(): Flow<UiState<${PASCAL_NAME}Entity>> = flow {
        emit(UiState.Loading)
        try {
            val response = apiService.get${PASCAL_NAME}Data()
            if (response.isSuccessful) {
                response.body()?.let { dto ->
                    emit(UiState.Success(dto.toEntity()))
                } ?: emit(UiState.Error("Empty response body"))
            } else {
                emit(UiState.Error("Server error: \${response.code()}"))
            }
        } catch (e: Exception) {
            emit(UiState.Error(e.message ?: "Unknown error occurred"))
        }
    }
}
EOF

# --- DI LAYER ---

# 7. DI Module
cat <<EOF > "$MODULE_FILE"
// Auto-generated by new_feature.sh
package ${PACKAGE_NAME}.di

import ${PACKAGE_NAME}.data.remote.${PASCAL_NAME}ApiService
import ${PACKAGE_NAME}.data.repository.${PASCAL_NAME}RepositoryImpl
import ${PACKAGE_NAME}.domain.repository.${PASCAL_NAME}Repository
import dagger.Binds
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import retrofit2.Retrofit
import javax.inject.Singleton

@Module
@InstallIn(SingletonComponent::class)
abstract class ${PASCAL_NAME}Module {

    @Binds
    @Singleton
    abstract fun bind${PASCAL_NAME}Repository(
        impl: ${PASCAL_NAME}RepositoryImpl
    ): ${PASCAL_NAME}Repository

    companion object {
        @Provides
        @Singleton
        fun provide${PASCAL_NAME}ApiService(retrofit: Retrofit): ${PASCAL_NAME}ApiService {
            return retrofit.create(${PASCAL_NAME}ApiService::class.java)
        }
    }
}
EOF

# --- PRESENTATION LAYER ---

# 8. ViewModel
cat <<EOF > "$VIEWMODEL_FILE"
// Auto-generated by new_feature.sh
package ${PACKAGE_NAME}.presentation.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import ${PACKAGE_NAME}.domain.model.${PASCAL_NAME}Entity
import ${PACKAGE_NAME}.domain.usecase.Get${PASCAL_NAME}UseCase
import ${BASE_PACKAGE}.utils.UiState
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class ${PASCAL_NAME}ViewModel @Inject constructor(
    private val get${PASCAL_NAME}UseCase: Get${PASCAL_NAME}UseCase
) : ViewModel() {

    private val _uiState = MutableStateFlow<UiState<${PASCAL_NAME}Entity>>(UiState.Loading)
    val uiState: StateFlow<UiState<${PASCAL_NAME}Entity>> = _uiState.asStateFlow()

    init {
        fetchData()
    }

    fun fetchData() {
        viewModelScope.launch {
            get${PASCAL_NAME}UseCase().collect { state ->
                _uiState.value = state
            }
        }
    }
}
EOF

# 9. Screen
cat <<EOF > "$SCREEN_FILE"
// Auto-generated by new_feature.sh
package ${PACKAGE_NAME}.presentation.ui

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import ${PACKAGE_NAME}.domain.model.${PASCAL_NAME}Entity
import ${PACKAGE_NAME}.presentation.viewmodel.${PASCAL_NAME}ViewModel
import ${BASE_PACKAGE}.utils.UiState
import androidx.compose.ui.tooling.preview.Preview

@Composable
fun ${PASCAL_NAME}Screen(
    viewModel: ${PASCAL_NAME}ViewModel = hiltViewModel()
) {
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()

    LaunchedEffect(Unit) {
        viewModel.fetchData()
    }

    Scaffold { paddingValues ->
        Box(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues),
            contentAlignment = Alignment.Center
        ) {
            when (val state = uiState) {
                is UiState.Loading -> {
                    CircularProgressIndicator()
                }
                is UiState.Success -> {
                    ${PASCAL_NAME}Content(data = state.data)
                }
                is UiState.Error -> {
                    Text(
                        text = "Error: \${state.message}",
                        color = MaterialTheme.colorScheme.error
                    )
                }
            }
        }
    }
}

@Composable
fun ${PASCAL_NAME}Content(data: ${PASCAL_NAME}Entity) {
    Column(horizontalAlignment = Alignment.CenterHorizontally) {
        Text(text = "Name: \${data.name}", style = MaterialTheme.typography.titleLarge)
        Text(text = "Description: \${data.description}", style = MaterialTheme.typography.bodyMedium)
    }
}

@Preview(showBackground = true)
@Composable
fun ${PASCAL_NAME}ScreenPreview() {
    MaterialTheme {
        ${PASCAL_NAME}Content(data = ${PASCAL_NAME}Entity(1, "Preview Name", "Preview Description"))
    }
}
EOF

# 10. Navigation Host
cat <<EOF > "$NAVHOST_FILE"
// Auto-generated by new_feature.sh
package ${PACKAGE_NAME}.presentation.navigation

import androidx.compose.runtime.Composable
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import ${PACKAGE_NAME}.presentation.ui.${PASCAL_NAME}Screen

object ${PASCAL_NAME}Routes {
    const val HOME = "${FEATURE}_home"
}

@Composable
fun ${PASCAL_NAME}Host() {
    val navController = rememberNavController()

    NavHost(navController = navController, startDestination = ${PASCAL_NAME}Routes.HOME) {
        composable(${PASCAL_NAME}Routes.HOME) {
            ${PASCAL_NAME}Screen()
        }
    }
}
EOF

echo ""
echo "✅ Successfully generated Clean Architecture feature: $FEATURE"
echo "Generated Structure in $FEATURE_PATH:"
echo "  [Domain]"
echo "  - domain/model/${PASCAL_NAME}Entity.kt"
echo "  - domain/repository/${PASCAL_NAME}Repository.kt"
echo "  - domain/usecase/Get${PASCAL_NAME}UseCase.kt"
echo "  [Data]"
echo "  - data/model/${PASCAL_NAME}Dto.kt"
echo "  - data/remote/${PASCAL_NAME}ApiService.kt"
echo "  - data/repository/${PASCAL_NAME}RepositoryImpl.kt"
echo "  [Presentation]"
echo "  - presentation/viewmodel/${PASCAL_NAME}ViewModel.kt"
echo "  - presentation/ui/${PASCAL_NAME}Screen.kt"
echo "  - presentation/navigation/${PASCAL_NAME}Host.kt"
echo "  [DI]"
echo "  - di/${PASCAL_NAME}Module.kt"
echo ""
echo "Don't forget to run Gradle Sync if your IDE doesn't pick them up automatically!"
