#!/usr/bin/env bash

# This script generates a full feature folder structure and required files
# for an Android Jetpack Compose MVVM project.

set -e

BASE_PACKAGE="com.example.app"
BASE_SRC_PATH="app/src/main/java/com/example/app"

show_help() {
    echo "Usage: ./new_feature.sh <feature_name>"
    echo ""
    echo "This script auto-generates a full feature folder structure for a Jetpack Compose MVVM project."
    echo "The feature name should be in lowercase (e.g., home)."
    echo ""
    echo "Example:"
    echo "  ./new_feature.sh home"
    echo "  ./new_feature.sh profile"
}

if [ "$#" -ne 1 ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    show_help
    exit 0
fi

FEATURE="$1"
# Capitalize the first letter for the PascalCase version (POSIX compliant)
PASCAL_NAME=$(echo "$FEATURE" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')

FEATURE_PATH="${BASE_SRC_PATH}/feature/${FEATURE}"
PACKAGE_NAME="${BASE_PACKAGE}.feature.${FEATURE}"

if [ -d "$FEATURE_PATH" ]; then
    echo "Error: Feature folder '$FEATURE_PATH' already exists."
    echo "Aborting to prevent overwriting existing files."
    exit 1
fi

echo "Generating feature: $FEATURE (Class prefix: $PASCAL_NAME)"

# Create directories
mkdir -p "${FEATURE_PATH}/data/model"
mkdir -p "${FEATURE_PATH}/data/remote"
mkdir -p "${FEATURE_PATH}/data/repository"
mkdir -p "${FEATURE_PATH}/di"
mkdir -p "${FEATURE_PATH}/ui"
mkdir -p "${FEATURE_PATH}/viewmodel"

# File Paths
MODEL_FILE="${FEATURE_PATH}/data/model/${PASCAL_NAME}Model.kt"
API_FILE="${FEATURE_PATH}/data/remote/${PASCAL_NAME}ApiService.kt"
REPO_FILE="${FEATURE_PATH}/data/repository/${PASCAL_NAME}Repository.kt"
MODULE_FILE="${FEATURE_PATH}/di/${PASCAL_NAME}Module.kt"
VIEWMODEL_FILE="${FEATURE_PATH}/viewmodel/${PASCAL_NAME}ViewModel.kt"
SCREEN_FILE="${FEATURE_PATH}/ui/${PASCAL_NAME}Screen.kt"

# 1. Model
cat <<EOF > "$MODEL_FILE"
// Auto-generated by new_feature.sh — do not delete this file
package ${PACKAGE_NAME}.data.model

import com.google.gson.annotations.SerializedName

data class ${PASCAL_NAME}Model(
    @SerializedName("id")
    val id: Int,
    @SerializedName("name")
    val name: String,
    @SerializedName("description")
    val description: String
)
EOF

# 2. ApiService
cat <<EOF > "$API_FILE"
// Auto-generated by new_feature.sh — do not delete this file
package ${PACKAGE_NAME}.data.remote

import ${PACKAGE_NAME}.data.model.${PASCAL_NAME}Model
import retrofit2.Response
import retrofit2.http.GET

interface ${PASCAL_NAME}ApiService {
    @GET("/${FEATURE}")
    suspend fun get${PASCAL_NAME}Data(): Response<${PASCAL_NAME}Model>
}
EOF

# 3. Repository
cat <<EOF > "$REPO_FILE"
// Auto-generated by new_feature.sh — do not delete this file
package ${PACKAGE_NAME}.data.repository

import ${PACKAGE_NAME}.data.model.${PASCAL_NAME}Model
import ${PACKAGE_NAME}.data.remote.${PASCAL_NAME}ApiService
import ${BASE_PACKAGE}.utils.UiState
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class ${PASCAL_NAME}Repository @Inject constructor(
    private val apiService: ${PASCAL_NAME}ApiService
) {
    suspend fun fetch${PASCAL_NAME}(): Flow<UiState<${PASCAL_NAME}Model>> = flow {
        emit(UiState.Loading)
        try {
            val response = apiService.get${PASCAL_NAME}Data()
            if (response.isSuccessful) {
                response.body()?.let {
                    emit(UiState.Success(it))
                } ?: emit(UiState.Error("Empty response body"))
            } else {
                emit(UiState.Error("Server error: \${response.code()}"))
            }
        } catch (e: Exception) {
            emit(UiState.Error(e.message ?: "Unknown error occurred"))
        }
    }
}
EOF

# 4. DI Module
cat <<EOF > "$MODULE_FILE"
// Auto-generated by new_feature.sh — do not delete this file
package ${PACKAGE_NAME}.di

import ${PACKAGE_NAME}.data.remote.${PASCAL_NAME}ApiService
import ${PACKAGE_NAME}.data.repository.${PASCAL_NAME}Repository
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import retrofit2.Retrofit
import javax.inject.Singleton

@Module
@InstallIn(SingletonComponent::class)
object ${PASCAL_NAME}Module {

    @Provides
    @Singleton
    fun provide${PASCAL_NAME}ApiService(retrofit: Retrofit): ${PASCAL_NAME}ApiService {
        return retrofit.create(${PASCAL_NAME}ApiService::class.java)
    }

    @Provides
    @Singleton
    fun provide${PASCAL_NAME}Repository(apiService: ${PASCAL_NAME}ApiService): ${PASCAL_NAME}Repository {
        return ${PASCAL_NAME}Repository(apiService)
    }
}
EOF

# 5. ViewModel
cat <<EOF > "$VIEWMODEL_FILE"
// Auto-generated by new_feature.sh — do not delete this file
package ${PACKAGE_NAME}.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import ${PACKAGE_NAME}.data.model.${PASCAL_NAME}Model
import ${PACKAGE_NAME}.data.repository.${PASCAL_NAME}Repository
import ${BASE_PACKAGE}.utils.UiState
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class ${PASCAL_NAME}ViewModel @Inject constructor(
    private val repository: ${PASCAL_NAME}Repository
) : ViewModel() {

    private val _uiState = MutableStateFlow<UiState<${PASCAL_NAME}Model>>(UiState.Loading)
    val uiState: StateFlow<UiState<${PASCAL_NAME}Model>> = _uiState.asStateFlow()

    init {
        fetchData()
    }

    fun fetchData() {
        viewModelScope.launch {
            repository.fetch${PASCAL_NAME}().collect { state ->
                _uiState.value = state
            }
        }
    }
}
EOF

# 6. Screen
cat <<EOF > "$SCREEN_FILE"
// Auto-generated by new_feature.sh — do not delete this file
package ${PACKAGE_NAME}.ui

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import ${PACKAGE_NAME}.data.model.${PASCAL_NAME}Model
import ${PACKAGE_NAME}.viewmodel.${PASCAL_NAME}ViewModel
import ${BASE_PACKAGE}.utils.UiState
import androidx.compose.ui.tooling.preview.Preview

@Composable
fun ${PASCAL_NAME}Screen(
    viewModel: ${PASCAL_NAME}ViewModel = hiltViewModel()
) {
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()

    LaunchedEffect(Unit) {
        viewModel.fetchData()
    }

    Scaffold { paddingValues ->
        Box(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues),
            contentAlignment = Alignment.Center
        ) {
            when (val state = uiState) {
                is UiState.Loading -> {
                    CircularProgressIndicator()
                }
                is UiState.Success -> {
                    ${PASCAL_NAME}Content(data = state.data)
                }
                is UiState.Error -> {
                    Text(
                        text = "Error: \${state.message}",
                        color = MaterialTheme.colorScheme.error
                    )
                }
            }
        }
    }
}

@Composable
fun ${PASCAL_NAME}Content(data: ${PASCAL_NAME}Model) {
    Column(horizontalAlignment = Alignment.CenterHorizontally) {
        Text(text = "Name: \${data.name}", style = MaterialTheme.typography.titleLarge)
        Text(text = "Description: \${data.description}", style = MaterialTheme.typography.bodyMedium)
    }
}

@Preview(showBackground = true)
@Composable
fun ${PASCAL_NAME}ScreenPreview() {
    MaterialTheme {
        ${PASCAL_NAME}Content(data = ${PASCAL_NAME}Model(1, "Preview Name", "Preview Description"))
    }
}
EOF

echo ""
echo "✅ Successfully generated feature: $FEATURE"
echo "The following files were created in $FEATURE_PATH:"
echo "  - data/model/${PASCAL_NAME}Model.kt"
echo "  - data/remote/${PASCAL_NAME}ApiService.kt"
echo "  - data/repository/${PASCAL_NAME}Repository.kt"
echo "  - di/${PASCAL_NAME}Module.kt"
echo "  - viewmodel/${PASCAL_NAME}ViewModel.kt"
echo "  - ui/${PASCAL_NAME}Screen.kt"
echo ""
echo "Don't forget to run Gradle Sync if your IDE doesn't pick them up automatically!"
