// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.activate.ui

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.example.app.feature.activate.data.model.ActivateModel
import com.example.app.feature.activate.viewmodel.ActivateViewModel
import com.example.app.utils.UiState
import androidx.compose.ui.tooling.preview.Preview

@Composable
fun ActivateScreen(
    viewModel: ActivateViewModel = hiltViewModel()
) {
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()

    LaunchedEffect(Unit) {
        viewModel.fetchData()
    }

    Scaffold { paddingValues ->
        Box(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues),
            contentAlignment = Alignment.Center
        ) {
            when (val state = uiState) {
                is UiState.Loading -> {
                    CircularProgressIndicator()
                }
                is UiState.Success -> {
                    ActivateContent(data = state.data)
                }
                is UiState.Error -> {
                    Text(
                        text = "Error: ${state.message}",
                        color = MaterialTheme.colorScheme.error
                    )
                }
            }
        }
    }
}

@Composable
fun ActivateContent(data: ActivateModel) {
    Column(horizontalAlignment = Alignment.CenterHorizontally) {
        Text(text = "Name: ${data.name}", style = MaterialTheme.typography.titleLarge)
        Text(text = "Description: ${data.description}", style = MaterialTheme.typography.bodyMedium)
    }
}

@Preview(showBackground = true)
@Composable
fun ActivateScreenPreview() {
    MaterialTheme {
        ActivateContent(data = ActivateModel(1, "Preview Name", "Preview Description"))
    }
}
