// Auto-generated by new_feature.sh
package com.example.app.feature.dora.di

import com.example.app.feature.dora.data.remote.DoraApiService
import com.example.app.feature.dora.data.repository.DoraRepositoryImpl
import com.example.app.feature.dora.domain.repository.DoraRepository
import dagger.Binds
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import retrofit2.Retrofit
import javax.inject.Singleton

@Module
@InstallIn(SingletonComponent::class)
abstract class DoraModule {

    @Binds
    @Singleton
    abstract fun bindDoraRepository(
        impl: DoraRepositoryImpl
    ): DoraRepository

    companion object {
        @Provides
        @Singleton
        fun provideDoraApiService(retrofit: Retrofit): DoraApiService {
            return retrofit.create(DoraApiService::class.java)
        }
    }
}
