// Auto-generated by new_feature.sh
package com.example.app.feature.dora.presentation.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.app.feature.dora.domain.model.DoraEntity
import com.example.app.feature.dora.domain.usecase.GetDoraUseCase
import com.example.app.utils.UiState
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class DoraViewModel @Inject constructor(
    private val getDoraUseCase: GetDoraUseCase
) : ViewModel() {

    private val _uiState = MutableStateFlow<UiState<DoraEntity>>(UiState.Loading)
    val uiState: StateFlow<UiState<DoraEntity>> = _uiState.asStateFlow()

    init {
        fetchData()
    }

    fun fetchData() {
        viewModelScope.launch {
            getDoraUseCase().collect { state ->
                _uiState.value = state
            }
        }
    }
}
