// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.product.data.remote

import com.example.app.feature.product.data.model.ProductModel
import retrofit2.Response
import retrofit2.http.GET

interface ProductApiService {
    @GET("/product")
    suspend fun getProductData(): Response<ProductModel>
}
