// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.comfort.di

import com.example.app.feature.comfort.data.remote.ComfortApiService
import com.example.app.feature.comfort.data.repository.ComfortRepository
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import retrofit2.Retrofit
import javax.inject.Singleton

@Module
@InstallIn(SingletonComponent::class)
object ComfortModule {

    @Provides
    @Singleton
    fun provideComfortApiService(retrofit: Retrofit): ComfortApiService {
        return retrofit.create(ComfortApiService::class.java)
    }

    @Provides
    @Singleton
    fun provideComfortRepository(apiService: ComfortApiService): ComfortRepository {
        return ComfortRepository(apiService)
    }
}
