// Auto-generated by new_feature.sh
package com.example.app.feature.dora.presentation.navigation

import androidx.compose.runtime.Composable
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import com.example.app.feature.dora.presentation.ui.DoraScreen

object DoraRoutes {
    const val HOME = "dora_home"
}

@Composable
fun DoraHost() {
    val navController = rememberNavController()

    NavHost(navController = navController, startDestination = DoraRoutes.HOME) {
        composable(DoraRoutes.HOME) {
            DoraScreen()
        }
    }
}
