// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.albums.data.remote

import com.example.app.feature.albums.data.model.AlbumsModel
import retrofit2.Response
import retrofit2.http.GET

interface AlbumsApiService {
    @GET("/albums")
    suspend fun getAlbumsData(): Response<List<AlbumsModel>>
}
