// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.albums.navigation

import androidx.compose.runtime.Composable
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import com.example.app.feature.albums.ui.AlbumsScreen

object AlbumsRoutes {
    const val HOME = "albums_home"
}

@Composable
fun AlbumsHost() {
    val navController = rememberNavController()

    NavHost(navController = navController, startDestination = AlbumsRoutes.HOME) {
        composable(AlbumsRoutes.HOME) {
            AlbumsScreen()
        }
    }
}
