// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.login.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.app.feature.login.data.model.LoginModel
import com.example.app.feature.login.data.repository.LoginRepository
import com.example.app.utils.UiState
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class LoginViewModel @Inject constructor(
    private val repository: LoginRepository
) : ViewModel() {

    private val _uiState = MutableStateFlow<UiState<LoginModel>>(UiState.Loading)
    val uiState: StateFlow<UiState<LoginModel>> = _uiState.asStateFlow()

    init {
        fetchData()
    }

    fun fetchData() {
        viewModelScope.launch {
            repository.fetchLogin().collect { state ->
                _uiState.value = state
            }
        }
    }
}
