// Auto-generated by new_feature.sh
package com.example.app.feature.dora.domain.repository

import com.example.app.feature.dora.domain.model.DoraEntity
import com.example.app.utils.UiState
import kotlinx.coroutines.flow.Flow

interface DoraRepository {
    suspend fun fetchDora(): Flow<UiState<DoraEntity>>
}
