// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.comfort.navigation

import androidx.compose.runtime.Composable
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import com.example.app.feature.comfort.ui.ComfortScreen

object ComfortRoutes {
    const val HOME = "comfort_home"
}

@Composable
fun ComfortHost() {
    val navController = rememberNavController()

    NavHost(navController = navController, startDestination = ComfortRoutes.HOME) {
        composable(ComfortRoutes.HOME) {
            ComfortScreen()
        }
    }
}
