// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.activate.data.remote

import com.example.app.feature.activate.data.model.ActivateModel
import retrofit2.Response
import retrofit2.http.GET

interface ActivateApiService {
    @GET("/activate")
    suspend fun getActivateData(): Response<ActivateModel>
}
