// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.comfort.data.repository

import com.example.app.feature.comfort.data.model.ComfortModel
import com.example.app.feature.comfort.data.remote.ComfortApiService
import com.example.app.utils.UiState
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class ComfortRepository @Inject constructor(
    private val apiService: ComfortApiService
) {
    suspend fun fetchComfort(): Flow<UiState<ComfortModel>> = flow {
        emit(UiState.Loading)
        try {
            val response = apiService.getComfortData()
            if (response.isSuccessful) {
                response.body()?.let {
                    emit(UiState.Success(it))
                } ?: emit(UiState.Error("Empty response body"))
            } else {
                emit(UiState.Error("Server error: ${response.code()}"))
            }
        } catch (e: Exception) {
            emit(UiState.Error(e.message ?: "Unknown error occurred"))
        }
    }
}
