// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.product.data.repository

import com.example.app.feature.product.data.model.ProductModel
import com.example.app.feature.product.data.remote.ProductApiService
import com.example.app.utils.UiState
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class ProductRepository @Inject constructor(
    private val apiService: ProductApiService
) {
    suspend fun fetchProduct(): Flow<UiState<ProductModel>> = flow {
        emit(UiState.Loading)
        try {
            val response = apiService.getProductData()
            if (response.isSuccessful) {
                response.body()?.let {
                    emit(UiState.Success(it))
                } ?: emit(UiState.Error("Empty response body"))
            } else {
                emit(UiState.Error("Server error: ${response.code()}"))
            }
        } catch (e: Exception) {
            emit(UiState.Error(e.message ?: "Unknown error occurred"))
        }
    }
}
