// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.comfort.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.app.feature.comfort.data.model.ComfortModel
import com.example.app.feature.comfort.data.repository.ComfortRepository
import com.example.app.utils.UiState
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class ComfortViewModel @Inject constructor(
    private val repository: ComfortRepository
) : ViewModel() {

    private val _uiState = MutableStateFlow<UiState<ComfortModel>>(UiState.Loading)
    val uiState: StateFlow<UiState<ComfortModel>> = _uiState.asStateFlow()

    init {
        fetchData()
    }

    fun fetchData() {
        viewModelScope.launch {
            repository.fetchComfort().collect { state ->
                _uiState.value = state
            }
        }
    }
}
