// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.login.data.repository

import com.example.app.feature.login.data.model.LoginModel
import com.example.app.feature.login.data.remote.LoginApiService
import com.example.app.utils.UiState
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class LoginRepository @Inject constructor(
    private val apiService: LoginApiService
) {
    suspend fun fetchLogin(): Flow<UiState<LoginModel>> = flow {
        emit(UiState.Loading)
        try {
            val response = apiService.getLoginData()
            if (response.isSuccessful) {
                response.body()?.let {
                    emit(UiState.Success(it))
                } ?: emit(UiState.Error("Empty response body"))
            } else {
                emit(UiState.Error("Server error: ${response.code()}"))
            }
        } catch (e: Exception) {
            emit(UiState.Error(e.message ?: "Unknown error occurred"))
        }
    }
}
