// Auto-generated by new_feature.sh
package com.example.app.feature.dora.domain.usecase

import com.example.app.feature.dora.domain.model.DoraEntity
import com.example.app.feature.dora.domain.repository.DoraRepository
import com.example.app.utils.UiState
import kotlinx.coroutines.flow.Flow
import javax.inject.Inject

class GetDoraUseCase @Inject constructor(
    private val repository: DoraRepository
) {
    suspend operator fun invoke(): Flow<UiState<DoraEntity>> {
        return repository.fetchDora()
    }
}
