// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.login.navigation

import androidx.compose.runtime.Composable
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import com.example.app.feature.login.ui.LoginScreen

object LoginRoutes {
    const val HOME = "login_home"
}

@Composable
fun LoginHost() {
    val navController = rememberNavController()

    NavHost(navController = navController, startDestination = LoginRoutes.HOME) {
        composable(LoginRoutes.HOME) {
            LoginScreen()
        }
    }
}
