// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.albums.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.app.feature.albums.data.model.AlbumsModel
import com.example.app.feature.albums.data.repository.AlbumsRepository
import com.example.app.utils.UiState
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class AlbumsViewModel @Inject constructor(
    private val repository: AlbumsRepository
) : ViewModel() {

    private val _uiState = MutableStateFlow<UiState<List<AlbumsModel>>>(UiState.Loading)
    val uiState: StateFlow<UiState<List<AlbumsModel>>> = _uiState.asStateFlow()

    init {
        fetchData()
    }

    fun fetchData() {
        viewModelScope.launch {
            repository.fetchAlbums().collect { state ->
                _uiState.value = state
            }
        }
    }
}
