// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.albums.data.model

import com.google.gson.annotations.SerializedName

data class AlbumsModel(
    @SerializedName("userId")
    val userId: Int,
    @SerializedName("id")
    val id: Int,
    @SerializedName("title")
    val title: String
)
