// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.activate.di

import com.example.app.feature.activate.data.remote.ActivateApiService
import com.example.app.feature.activate.data.repository.ActivateRepository
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import retrofit2.Retrofit
import javax.inject.Singleton

@Module
@InstallIn(SingletonComponent::class)
object ActivateModule {

    @Provides
    @Singleton
    fun provideActivateApiService(retrofit: Retrofit): ActivateApiService {
        return retrofit.create(ActivateApiService::class.java)
    }

    @Provides
    @Singleton
    fun provideActivateRepository(apiService: ActivateApiService): ActivateRepository {
        return ActivateRepository(apiService)
    }
}
