// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.login.data.remote

import com.example.app.feature.login.data.model.LoginModel
import retrofit2.Response
import retrofit2.http.GET

interface LoginApiService {
    @GET("/login")
    suspend fun getLoginData(): Response<LoginModel>
}
