// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.activate.data.repository

import com.example.app.feature.activate.data.model.ActivateModel
import com.example.app.feature.activate.data.remote.ActivateApiService
import com.example.app.utils.UiState
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class ActivateRepository @Inject constructor(
    private val apiService: ActivateApiService
) {
    suspend fun fetchActivate(): Flow<UiState<ActivateModel>> = flow {
        emit(UiState.Loading)
        try {
            val response = apiService.getActivateData()
            if (response.isSuccessful) {
                response.body()?.let {
                    emit(UiState.Success(it))
                } ?: emit(UiState.Error("Empty response body"))
            } else {
                emit(UiState.Error("Server error: ${response.code()}"))
            }
        } catch (e: Exception) {
            emit(UiState.Error(e.message ?: "Unknown error occurred"))
        }
    }
}
