// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.activate.data.model

import com.google.gson.annotations.SerializedName

data class ActivateModel(
    @SerializedName("id")
    val id: Int,
    @SerializedName("name")
    val name: String,
    @SerializedName("description")
    val description: String
)
