// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.albums.data.repository

import com.example.app.feature.albums.data.model.AlbumsModel
import com.example.app.feature.albums.data.remote.AlbumsApiService

import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class AlbumsRepository @Inject constructor(
    private val apiService: AlbumsApiService
) {
    suspend fun fetchAlbums(page: Int, limit: Int = 20): Result<List<AlbumsModel>> {
        return try {
            val response = apiService.getAlbumsData(page, limit)
            if (response.isSuccessful) {
                Result.success(response.body() ?: emptyList())
            } else {
                Result.failure(Exception("Server error: ${response.code()}"))
            }
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}
