// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.albums.data.repository

import com.example.app.feature.albums.data.model.AlbumsModel
import com.example.app.feature.albums.data.remote.AlbumsApiService
import com.example.app.utils.UiState
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class AlbumsRepository @Inject constructor(
    private val apiService: AlbumsApiService
) {
    suspend fun fetchAlbums(): Flow<UiState<List<AlbumsModel>>> = flow {
        emit(UiState.Loading)
        try {
            val response = apiService.getAlbumsData()
            if (response.isSuccessful) {
                response.body()?.let {
                    emit(UiState.Success(it))
                } ?: emit(UiState.Error("Empty response body"))
            } else {
                emit(UiState.Error("Server error: ${response.code()}"))
            }
        } catch (e: Exception) {
            emit(UiState.Error(e.message ?: "Unknown error occurred"))
        }
    }
}
