// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.product.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.app.feature.product.data.model.ProductModel
import com.example.app.feature.product.data.repository.ProductRepository
import com.example.app.utils.UiState
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class ProductViewModel @Inject constructor(
    private val repository: ProductRepository
) : ViewModel() {

    private val _uiState = MutableStateFlow<UiState<ProductModel>>(UiState.Loading)
    val uiState: StateFlow<UiState<ProductModel>> = _uiState.asStateFlow()

    init {
        fetchData()
    }

    fun fetchData() {
        viewModelScope.launch {
            repository.fetchProduct().collect { state ->
                _uiState.value = state
            }
        }
    }
}
