// Auto-generated by new_feature.sh
package com.example.app.feature.dora.data.model

import com.google.gson.annotations.SerializedName
import com.example.app.feature.dora.domain.model.DoraEntity

data class DoraDto(
    @SerializedName("id")
    val id: Int?,
    @SerializedName("name")
    val name: String?,
    @SerializedName("description")
    val description: String?
)

// Extension function to map DTO to Domain Entity
fun DoraDto.toEntity(): DoraEntity {
    return DoraEntity(
        id = this.id ?: 0,
        name = this.name.orEmpty(),
        description = this.description.orEmpty()
    )
}
