// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.comfort.data.remote

import com.example.app.feature.comfort.data.model.ComfortModel
import retrofit2.Response
import retrofit2.http.GET

interface ComfortApiService {
    @GET("/comfort")
    suspend fun getComfortData(): Response<ComfortModel>
}
