// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.albums.di

import com.example.app.feature.albums.data.remote.AlbumsApiService
import com.example.app.feature.albums.data.repository.AlbumsRepository
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import retrofit2.Retrofit
import javax.inject.Singleton

@Module
@InstallIn(SingletonComponent::class)
object AlbumsModule {

    @Provides
    @Singleton
    fun provideAlbumsApiService(retrofit: Retrofit): AlbumsApiService {
        return retrofit.create(AlbumsApiService::class.java)
    }

    @Provides
    @Singleton
    fun provideAlbumsRepository(apiService: AlbumsApiService): AlbumsRepository {
        return AlbumsRepository(apiService)
    }
}
