// Auto-generated by new_feature.sh
package com.example.app.feature.dora.data.repository

import com.example.app.feature.dora.data.remote.DoraApiService
import com.example.app.feature.dora.data.model.toEntity
import com.example.app.feature.dora.domain.model.DoraEntity
import com.example.app.feature.dora.domain.repository.DoraRepository
import com.example.app.utils.UiState
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class DoraRepositoryImpl @Inject constructor(
    private val apiService: DoraApiService
) : DoraRepository {

    override suspend fun fetchDora(): Flow<UiState<DoraEntity>> = flow {
        emit(UiState.Loading)
        try {
            val response = apiService.getDoraData()
            if (response.isSuccessful) {
                response.body()?.let { dto ->
                    emit(UiState.Success(dto.toEntity()))
                } ?: emit(UiState.Error("Empty response body"))
            } else {
                emit(UiState.Error("Server error: ${response.code()}"))
            }
        } catch (e: Exception) {
            emit(UiState.Error(e.message ?: "Unknown error occurred"))
        }
    }
}
