// Auto-generated by new_feature.sh — do not delete this file
package com.example.app.feature.login.di

import com.example.app.feature.login.data.remote.LoginApiService
import com.example.app.feature.login.data.repository.LoginRepository
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import retrofit2.Retrofit
import javax.inject.Singleton

@Module
@InstallIn(SingletonComponent::class)
object LoginModule {

    @Provides
    @Singleton
    fun provideLoginApiService(retrofit: Retrofit): LoginApiService {
        return retrofit.create(LoginApiService::class.java)
    }

    @Provides
    @Singleton
    fun provideLoginRepository(apiService: LoginApiService): LoginRepository {
        return LoginRepository(apiService)
    }
}
