// Auto-generated by new_feature.sh
package com.example.app.feature.dora.data.remote

import com.example.app.feature.dora.data.model.DoraDto
import retrofit2.Response
import retrofit2.http.GET

interface DoraApiService {
    @GET("/dora")
    suspend fun getDoraData(): Response<DoraDto>
}
